# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160514_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
