# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 00:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_updated',
            field=models.DateField(auto_now=True, db_index=True, default=datetime.datetime(2016, 5, 22, 0, 28, 50, 846553, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
